test(object): add side project test for SSE
This test doesn't pass, while the same manual test is fine.
Here is the error:

bucket_server_side_encryption_configuration_test.go:73: Step 2/2 error running import: exit status 1
    Error: Cannot import non-existent remote object

    While attempting to import an existing object to
    "scaleway_object_bucket_server_side_encryption_configuration.test", the
    provider detected that no object exists with the given id. Only pre-existing
    objects can be imported; check that the id is correct and that it is
    associated with the provider's configured region or endpoint, or use
    "terraform apply" to create a new remote object for this resource.

Thus accounting for the ID changes I made in previous attempts.