feat(object): add project_id to bucket sse (#4119)
* feat(object): add project_id to bucket sse

This change fixed the issue for the user error: we can now attach a
scaleway_object_bucket_server_side_encryption to a bucket from another
project.

I don't understand how it fixes the issue, and why the issue exists in
the first place.

* feat(object): add project_id to bucket sse data source

* test(object): update cassettes

* test(object): add side project test for SSE

This test doesn't pass, while the same manual test is fine.
Here is the error:

bucket_server_side_encryption_configuration_test.go:73: Step 2/2 error running import: exit status 1
    Error: Cannot import non-existent remote object

    While attempting to import an existing object to
    "scaleway_object_bucket_server_side_encryption_configuration.test", the
    provider detected that no object exists with the given id. Only pre-existing
    objects can be imported; check that the id is correct and that it is
    associated with the provider's configured region or endpoint, or use
    "terraform apply" to create a new remote object for this resource.

Thus accounting for the ID changes I made in previous attempts.

* test(object): fix side project test

* test(object): check bucket sse project_id

* test(object): update cassettes

* test(object): make warning comment clearer

* docs(object): add project_id to sse

* chore(object): refactor into setProjectIDFromACL

* docs(object): run make docs

* test(object): update cassette

* chore(object): format

* test(object): check destroy for SSE as well